spring:
  application:
    name: API de Beneficiario
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
    name: Growth7CalendarDBConnection
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: false

server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    context-path: /beneficiario-api/v1

springdoc:
  swagger-ui:
    doc-expansion: list
    tags-sorter: alpha

logging:
  level:
    root: INFO
    br.com.ekan.beneficiario.api: DEBUG
    org.springframework.boot: ERROR
    org.springframework.context: ERROR
    org.springframework.beans: ERROR
    org.springframework.web: ERROR
    org.springframework.jdbc: DEBUG
    org.springframework.security: ERROR
    org.springframework: ERROR # Configura todos os outros pacotes Spring para ERROR para minimizar ruído
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    
api:
  info:
    title: "@name@"
    description: "@description@"
    version: "@version@"
    termsOfServiceUrl: https://ekan.com.br/legal/termos.html
    contact:
      name: Equipe Ekan
      url: https://ekan.com.br/contato.html
      email: contato@ekan.com.br
    license: Copyright 2023 Ekan - Todos os direitos reservados.
    licenseUrl: https://ekan.com.br/legal/licenca.html
  auth:
    header:
      token:
        key: "${TOKEN_KEY:x-auth-secret-key}"
        value: "${TOKEN_VALUE:123456}"
    